# fly.toml app configuration file generated for young-sky-895 on 2023-08-16T18:40:48-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "young-sky-895"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
